### ISSUE TITLE
exit hangs with disabled threads

### ISSUE THREAD

**Issue by pavel-demin** [gustafn/nsf#2]
Hello,

I'm trying to migrate from XOTcl 1.6.8 to XOTcl 2.3.0 and I've noticed that if Tcl 8.6 and NSF 2.3.0 are built with disabled threads, then the exit command doesn't work after loading the XOTcl package.

Here are the commands to reproduce the problem:
```
TCL_DIR=$PWD/tcl

curl -LO https://sourceforge.net/projects/tcl/files/Tcl/8.6.9/tcl8.6.9-src.tar.gz
tar -zxf tcl8.6.9-src.tar.gz

curl -LO https://sourceforge.net/projects/next-scripting/files/2.3.0/nsf2.3.0.tar.gz
tar -zxf nsf2.3.0.tar.gz

cd tcl8.6.9

sh unix/configure --disable-threads --prefix=$TCL_DIR --exec-prefix=$TCL_DIR
make install-binaries install-libraries install-headers

cd -

cd nsf2.3.0

sh configure --disable-threads --prefix=$TCL_DIR --exec-prefix=$TCL_DIR --with-tcl=$TCL_DIR/lib
make install-binaries install-libraries install-xotcl-libraries

cd -

./tcl/bin/tclsh8.6

% package require XOTcl
2.3
% exit
Warning: The class ::nx::Object, from which an instance is to be removed, is currently under deletion
```

Best regards,

Pavel

**Comment by gustafn** [comment]
Dear Pavel,

many thanks for the good report. Yes, there was a problem at exit, when compiled 
without thread support (we should add this to our test cases). The last changes,
especially https://github.com/gustafn/nsf/commit/8dbedb9a954b6d9de577b60067bcb9806acd0e35 fixed this issue.

Let me know, when i can help in the migration.
all the best 
-gustaf

**Comment by pavel-demin** [comment]
Thank you very much for fixing this problem. I've just tested the code from the master branch and it works flawlessly. My application ([a SOAP server](https://github.com/pavel-demin/srmlite/tree/master/server)) works with XOTcl 2.4.0 without any modifications.
